### ISSUE TITLE
Fancy hover boxes have too much space in between each other

### ISSUE THREAD

**Issue by ZeeCote** [ZeeCote/fancy-hover-boxes#1]
Ive added img { width: 100%} and that made markbot accept the medium and large website but its still saying that the small screen size is too small, I tried removing margin and padding from the img, the section and the h2 but none of these are fixing my issue. I've followed the lesson to a tea and checked it multiple times. 
@JessJodoin
@hellachella

**Comment by JessJodoin** [comment]
On `<img>` tags, the default display is` display: inline-block;` which adds a weird space. So just add `display: block;` to your `<img>` tags in your css and that should fix it 😄
